/**
 * Figma design token sync — run with:
 *   npm run tokens:sync    — import tokens.json → generated SCSS
 *   npm run tokens:export  — export current tokens.json from SCSS values
 *   npm run tokens:verify  — fail if JSON and generated SCSS are out of sync
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SCSS_NAME } from './figma-token-bridge.ts';
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const TOKENS_JSON = join(ROOT, 'src/design-system/tokens/figma/tokens.json');
const GENERATED_SCSS = join(ROOT, 'src/design-system/tokens/figma/generated/_tokens.scss');

type TokenLeaf = {
  $type?: string;
  $value: unknown;
};

type FlatToken = {
  path: string;
  type: string;
  rawValue: unknown;
  resolvedValue: unknown;
};

const REFERENCE_VARS = new Set([
  '$ds-color-text-link',
  '$ds-color-border-focus',
  '$ds-spacer',
  '$ps-shadow-overlay',
]);

function isTokenLeaf(node: unknown): node is TokenLeaf {
  return (
    typeof node === 'object' &&
    node !== null &&
    '$value' in node &&
    !Array.isArray(node)
  );
}

function flattenTokens(node: unknown, prefix = ''): FlatToken[] {
  if (isTokenLeaf(node)) {
    return [
      {
        path: prefix,
        type: node.$type ?? 'unknown',
        rawValue: node.$value,
        resolvedValue: node.$value,
      },
    ];
  }

  if (typeof node !== 'object' || node === null || Array.isArray(node)) {
    return [];
  }

  const entries: FlatToken[] = [];
  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    const path = prefix ? `${prefix}.${key}` : key;
    entries.push(...flattenTokens(value, path));
  }
  return entries;
}

function resolveReferences(tokens: FlatToken[]): FlatToken[] {
  const byPath = new Map(tokens.map((t) => [t.path, t]));
  const resolving = new Set<string>();

  function resolve(path: string, raw: unknown): unknown {
    if (typeof raw !== 'string' || !raw.startsWith('{') || !raw.endsWith('}')) {
      return raw;
    }

    const refPath = raw.slice(1, -1);
    if (resolving.has(refPath)) {
      throw new Error(`Circular token reference: ${refPath}`);
    }

    const ref = byPath.get(refPath);
    if (!ref) {
      throw new Error(`Unresolved token reference: ${raw}`);
    }

    resolving.add(refPath);
    const resolved = resolve(refPath, ref.rawValue);
    resolving.delete(refPath);
    return resolved;
  }

  return tokens.map((token) => ({
    ...token,
    resolvedValue: resolve(token.path, token.rawValue),
  }));
}

function formatScssValue(name: string, type: string, value: unknown): string {
  if (REFERENCE_VARS.has(name)) {
    const refPath = Object.entries(SCSS_NAME).find(([, scss]) => scss === name)?.[0];
    if (!refPath) throw new Error(`Missing reference mapping for ${name}`);

    if (name === '$ds-color-text-link' || name === '$ds-color-border-focus') {
      return '$ds-color-accent';
    }
    if (name === '$ds-spacer') {
      return '$ds-space-3';
    }
    if (name === '$ps-shadow-overlay') {
      return '$ds-shadow-lg';
    }
  }

  if (type === 'fontFamily' && Array.isArray(value)) {
    return value.map((part) => (part.includes(' ') ? `'${part}'` : part)).join(', ');
  }

  if (type === 'number' || type === 'fontWeight') {
    return String(value);
  }

  if (type === 'cubicBezier' && Array.isArray(value)) {
    return `cubic-bezier(${(value as number[]).join(', ')})`;
  }

  return String(value);
}

function generateScss(tokens: FlatToken[]): string {
  const lines = [
    '/**',
    ' * Figma token values — generated by scripts/sync-figma-tokens.ts',
    ' * Source: src/design-system/tokens/figma/tokens.json',
    ' * Do not edit manually. Run: npm run tokens:sync',
    ' */',
    '',
  ];

  const groups: Record<string, FlatToken[]> = {
    color: [],
    font: [],
    space: [],
    radius: [],
    shadow: [],
    transition: [],
    ease: [],
    product: [],
  };

  for (const token of tokens) {
    const group = token.path.split('.')[0] ?? 'other';
    (groups[group] ??= []).push(token);
  }

  const groupOrder = ['color', 'font', 'space', 'radius', 'shadow', 'transition', 'ease', 'product'];

  for (const group of groupOrder) {
    const groupTokens = groups[group];
    if (!groupTokens?.length) continue;

    lines.push(`// ${group}`);
    for (const token of groupTokens) {
      const name = SCSS_NAME[token.path];
      if (!name) {
        throw new Error(`No SCSS mapping for token path: ${token.path}`);
      }
      const value = formatScssValue(name, token.type, token.resolvedValue);
      lines.push(`${name}: ${value};`);
    }
    lines.push('');
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function parseGeneratedScss(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const line of content.split('\n')) {
    const match = line.match(/^(\$[\w-]+):\s*(.+);$/);
    if (match) {
      map.set(match[1]!, match[2]!.trim());
    }
  }
  return map;
}

function loadJsonTokens(): FlatToken[] {
  const raw = JSON.parse(readFileSync(TOKENS_JSON, 'utf8')) as Record<string, unknown>;
  const flat = flattenTokens(raw);
  return resolveReferences(flat);
}

function cmdSync(): void {
  const tokens = loadJsonTokens();
  const scss = generateScss(tokens);
  mkdirSync(dirname(GENERATED_SCSS), { recursive: true });
  writeFileSync(GENERATED_SCSS, scss, 'utf8');
  console.log(`✓ Generated ${GENERATED_SCSS.replace(`${ROOT}/`, '')}`);
  console.log(`  ${tokens.length} tokens synced from Figma JSON`);
}

function cmdVerify(): void {
  const tokens = loadJsonTokens();
  const expected = generateScss(tokens);

  if (!existsSync(GENERATED_SCSS)) {
    throw new Error('Generated SCSS missing — run npm run tokens:sync');
  }

  const actual = readFileSync(GENERATED_SCSS, 'utf8');
  if (actual !== expected) {
    throw new Error(
      'Figma tokens out of sync. Run npm run tokens:sync after updating tokens.json',
    );
  }

  console.log(`✓ Figma tokens verified (${tokens.length} tokens)`);
}

function cmdExport(): void {
  if (!existsSync(GENERATED_SCSS)) {
    throw new Error('Generated SCSS missing — run npm run tokens:sync first');
  }

  const generated = parseGeneratedScss(readFileSync(GENERATED_SCSS, 'utf8'));
  const existing = JSON.parse(readFileSync(TOKENS_JSON, 'utf8')) as Record<string, unknown>;

  function exportNode(node: unknown, path = ''): unknown {
    if (isTokenLeaf(node)) {
      const scssName = SCSS_NAME[path];
      if (!scssName) return node;

      if (REFERENCE_VARS.has(scssName)) {
        return node;
      }

      const value = generated.get(scssName);
      if (value === undefined) return node;

      let jsonValue: unknown = value;
      if (node.$type === 'fontFamily') {
        jsonValue = value.split(',').map((part) => part.trim().replace(/^'|'$/g, ''));
      } else if (node.$type === 'number' || node.$type === 'fontWeight') {
        jsonValue = Number(value);
      } else if (node.$type === 'cubicBezier') {
        const match = value.match(/cubic-bezier\(([^)]+)\)/);
        jsonValue = match
          ? match[1]!.split(',').map((n) => Number(n.trim()))
          : node.$value;
      }

      return { ...node, $value: jsonValue };
    }

    if (typeof node !== 'object' || node === null || Array.isArray(node)) {
      return node;
    }

    const result: Record<string, unknown> = {};
    for (const [key, value] of Object.entries(node)) {
      if (key.startsWith('$')) {
        result[key] = value;
        continue;
      }
      const childPath = path ? `${path}.${key}` : key;
      result[key] = exportNode(value, childPath);
    }
    return result;
  }

  const exported = exportNode(existing) as Record<string, unknown>;
  writeFileSync(TOKENS_JSON, `${JSON.stringify(exported, null, 2)}\n`, 'utf8');
  console.log(`✓ Exported values to ${TOKENS_JSON.replace(`${ROOT}/`, '')}`);
}

function main(): void {
  const command = process.argv[2] ?? 'sync';

  switch (command) {
    case 'sync':
      cmdSync();
      break;
    case 'verify':
      cmdVerify();
      break;
    case 'export':
      cmdExport();
      break;
    default:
      throw new Error(`Unknown command: ${command}. Use sync, verify, or export.`);
  }
}

try {
  main();
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
